name: Publish to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
           python-version: '3.11'

      - name: Installing Sphinx
        run: |
          pip install sphinx
          pip install https://github.com/ghislainv/riskmapjnr/archive/master.zip

      - name: Building documentation
        run: sphinx-build docsrc docs/html -b html -d docs/doctree

      - name: Adding nojekyll file
        run: touch docs/html/.nojekyll

      - name: Deploy generated content to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: docs/html
